export const convexFunctions = {
  users: {
    createUser: "users:createUser",
    getUserByEmail: "users:getUserByEmail",
    getUserByEmailWithPassword: "users:getUserByEmailWithPassword",
    getUserById: "users:getUserById",
  },
  ai: {
    generateImageWithGemini: "ai:generateImageWithGemini",
    generateImageWithReplicate: "ai:generateImageWithReplicate",
    generateCodeWithGemini: "ai:generateCodeWithGemini",
    generateVideoWithGemini: "ai:generateVideoWithGemini",
    generateVideoWithReplicate: "ai:generateVideoWithReplicate",
    generateAudioWithGemini: "ai:generateAudioWithGemini",
    generateAudioWithReplicate: "ai:generateAudioWithReplicate",
    generateConversationReplyWithGemini: "ai:generateConversationReplyWithGemini",
    listGenerationsByUserAndKind: "ai:listGenerationsByUserAndKind",
    listGenerationsBySession: "ai:listGenerationsBySession",
    listImageGenerationsByUser: "ai:listImageGenerationsByUser",
    listAudioGenerationsByUser: "ai:listAudioGenerationsByUser",
    listVideoGenerationsByUser: "ai:listVideoGenerationsByUser",
    getImageStorageUrl: "ai:getImageStorageUrl",
    getSessionById: "ai:getSessionById",
    listSessionsByUserAndKind: "ai:listSessionsByUserAndKind",
    createSession: "ai:createSession",
    updateSessionTitle: "ai:updateSessionTitle",
    deleteSession: "ai:deleteSession",
    deleteGeneration: "ai:deleteGeneration",
    recordGeneration: "ai:recordGeneration",
  },
  billing: {
    seedDefaultPlans: "billing:seedDefaultPlans",
    listPlans: "billing:listPlans",
    getCurrentUserPlan: "billing:getCurrentUserPlan",
    setUserPlan: "billing:setUserPlan",
    grantAdminRole: "billing:grantAdminRole",
    revokeAdminRole: "billing:revokeAdminRole",
    getUsageSummary: "billing:getUsageSummary",
    trackUsageAndEnforcePlan: "billing:trackUsageAndEnforcePlan",
  },
  admin: {
    getDashboardSnapshot: "admin:getDashboardSnapshot",
    setUserAccountStatus: "admin:setUserAccountStatus",
    setUserPlanAsAdmin: "admin:setUserPlanAsAdmin",
  },
} as const;
